### ISSUE TITLE
As a Guest User, I'd like to copy the direct Avatar URL, so I can navigate to it directly via the address bar of a web browser

### ISSUE THREAD

**Issue by elmerbool** [ei8/cortex-diary#15]
Notes:
1. "Copy Direct Avatar URL" button 
2. Place directly above "First At Top"
![image](https://user-images.githubusercontent.com/35117496/155134560-c249cae2-ce4d-429d-8180-0b4f886d993d.png)
3. Copy to clipboard

**Comment by erwintayag** [comment]
Included some UI Adjustments as requested:
1. Alignment of menu item
2. Use information toast instead of success
3. Use substring of the base directory ("/tree?)
