### ISSUE TITLE
As a Guest User, I'd like to minimize or restore the left sidebar when in Desktop mode/view, so I can increase the size of the main panel when necessary

### ISSUE THREAD

**Issue by elmerbool** [ei8/cortex-diary#16]
Samples:
1. https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapse_sidebar
2. https://stackoverflow.com/questions/59048009/mimize-default-blazor-navmenu-in-sidebar

**Comment by erwintayag** [comment]
Resources used to implement the changes:
[Blazorise](https://blazorise.com/docs) _(Navbar disappears on mobile screen)_
[DanielHWe's Answer on GitHub](https://github.com/DanielHWe/Hide-Blazor-NavBar-Sample)
[Syncfusion](https://blazor.syncfusion.com/demos/sidebar/sidebar-with-menu?theme=bootstrap5) _(Paid)_

**Comment by elmerbool** [comment]
Hi Erwin, 

Thanks for committing the changes for this ticket. 

The following are the UI review/test findings:
1. Keep the sidebar visible by only minimizing (width:65px)? it rather than hiding it. Sample below.
![image](https://user-images.githubusercontent.com/35117496/158041671-608bc571-6f94-44e6-b2eb-7850613a865d.png)
2. Might require re-styling of sign-in button and app logo (px-2 instead of px-3) so that it fits in the minimized sidebar.
3. Relocate minimize/restore toggle to inside the sidebar. Perhaps right above the "signin" button?
4. Might need to hide all text (buttons, logo text, signin etc.) in side bar when minimized.
5. If a sidebar nav button is active, it's caption should be appended to the browser tab text. 
![image](https://user-images.githubusercontent.com/35117496/158042026-5aae0a8b-aae6-49f4-b0ae-4fea1a701474.png)

A few code review items were found but can be discussed or revisited later during refactor/optimization.

**Comment by elmerbool** [comment]
@erwintayag , this blazorise sidebar sample might help -
https://github.com/Megabit/Blazorise/issues/1241
