### ISSUE TITLE
As a Guest User, I'd like to edit the avatar query parameters using a dialog box, so I can easily change the parameters of the Avatar URL

### ISSUE THREAD

**Issue by elmerbool** [ei8/cortex-diary#44]

**Comment by abdooAhmed** [comment]
Milestone 1:
1. Button on right side of avatar url textbox - "Edit Parameters" (tooltip), Icon
2. #1 displays popup menu
3. Popup has 2 buttons - Apply, X (Cancel)
4. Popup has 1 textbox for TagContains
